version: '3'
services:
  # dnsmasq:
  #   restart: always
  #   image: andyshinn/dnsmasq
  #   ports:
  #     - "53:53/udp"
  #     - "53:53/tcp"
  #   extra_hosts:
  #     - "local.example.com:127.0.0.1"
  #   cap_add:
  #     - NET_ADMIN
  #   volumes:
  #     - ./dnsmasq.conf:/etc/dnsmasq.conf
  mysql:
    restart: always
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: pass
    volumes:
    - ./mysql/data:/var/lib/mysql
    - ./mysql/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
    ports:
    - 3306:3306
  redis:
    restart: always
    image: redis:3
    ports:
      - "6379:6379"
  # ab:
  #   build: ./docker/ab
  #   image: my/ab
  #   tty: true
  #   stdin_open: true
  #   entrypoint: /bin/sh
  # postgresql:
  #   image: postgres:10.5
  #   ports:
  #     - 5432:5432
  #   environment:
  #     POSTGRES_USER: root
  #     POSTGRES_PASSWORD: root
  #     POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
  #   user: root
  nginx:
    image: 'nginx:1-alpine'
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/servers.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/server.crt:/etc/nginx/server.crt
      - ./docker/nginx/server.key:/etc/nginx/server.key
      - /Users/thr3a/nodejs/skytree:/app
    restart: always
  python:
    build: ./docker/python
    image: my/python
    ports:
      - "30000:8888"
    environment:
      JUPYTER_ENABLE_LAB: 1
    volumes:
      - ./workspace:/home/jovyan